/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioIdRouteImport } from './routes/portfolio.$id'
import { Route as LongHorizonIdRouteImport } from './routes/long-horizon.$id'
import { Route as ApiPublicHooksLiveReconcileRouteImport } from './routes/api/public/hooks/live-reconcile'
import { Route as ApiPublicHooksHourlyRunRouteImport } from './routes/api/public/hooks/hourly-run'
import { Route as ApiPublicHooksDailyRunRouteImport } from './routes/api/public/hooks/daily-run'
import { Route as AuthenticatedPortfolioIdAttributionRouteImport } from './routes/_authenticated.portfolio.$id.attribution'

const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIdRoute = PortfolioIdRouteImport.update({
  id: '/portfolio/$id',
  path: '/portfolio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LongHorizonIdRoute = LongHorizonIdRouteImport.update({
  id: '/long-horizon/$id',
  path: '/long-horizon/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksLiveReconcileRoute =
  ApiPublicHooksLiveReconcileRouteImport.update({
    id: '/api/public/hooks/live-reconcile',
    path: '/api/public/hooks/live-reconcile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksHourlyRunRoute = ApiPublicHooksHourlyRunRouteImport.update({
  id: '/api/public/hooks/hourly-run',
  path: '/api/public/hooks/hourly-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailyRunRoute = ApiPublicHooksDailyRunRouteImport.update({
  id: '/api/public/hooks/daily-run',
  path: '/api/public/hooks/daily-run',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortfolioIdAttributionRoute =
  AuthenticatedPortfolioIdAttributionRouteImport.update({
    id: '/_authenticated/portfolio/$id/attribution',
    path: '/portfolio/$id/attribution',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/get-started': typeof GetStartedRoute
  '/long-horizon/$id': typeof LongHorizonIdRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/portfolio/$id/attribution': typeof AuthenticatedPortfolioIdAttributionRoute
  '/api/public/hooks/daily-run': typeof ApiPublicHooksDailyRunRoute
  '/api/public/hooks/hourly-run': typeof ApiPublicHooksHourlyRunRoute
  '/api/public/hooks/live-reconcile': typeof ApiPublicHooksLiveReconcileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/get-started': typeof GetStartedRoute
  '/long-horizon/$id': typeof LongHorizonIdRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/portfolio/$id/attribution': typeof AuthenticatedPortfolioIdAttributionRoute
  '/api/public/hooks/daily-run': typeof ApiPublicHooksDailyRunRoute
  '/api/public/hooks/hourly-run': typeof ApiPublicHooksHourlyRunRoute
  '/api/public/hooks/live-reconcile': typeof ApiPublicHooksLiveReconcileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/get-started': typeof GetStartedRoute
  '/long-horizon/$id': typeof LongHorizonIdRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/_authenticated/portfolio/$id/attribution': typeof AuthenticatedPortfolioIdAttributionRoute
  '/api/public/hooks/daily-run': typeof ApiPublicHooksDailyRunRoute
  '/api/public/hooks/hourly-run': typeof ApiPublicHooksHourlyRunRoute
  '/api/public/hooks/live-reconcile': typeof ApiPublicHooksLiveReconcileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/compare'
    | '/get-started'
    | '/long-horizon/$id'
    | '/portfolio/$id'
    | '/portfolio/$id/attribution'
    | '/api/public/hooks/daily-run'
    | '/api/public/hooks/hourly-run'
    | '/api/public/hooks/live-reconcile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/compare'
    | '/get-started'
    | '/long-horizon/$id'
    | '/portfolio/$id'
    | '/portfolio/$id/attribution'
    | '/api/public/hooks/daily-run'
    | '/api/public/hooks/hourly-run'
    | '/api/public/hooks/live-reconcile'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/compare'
    | '/get-started'
    | '/long-horizon/$id'
    | '/portfolio/$id'
    | '/_authenticated/portfolio/$id/attribution'
    | '/api/public/hooks/daily-run'
    | '/api/public/hooks/hourly-run'
    | '/api/public/hooks/live-reconcile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  GetStartedRoute: typeof GetStartedRoute
  LongHorizonIdRoute: typeof LongHorizonIdRoute
  PortfolioIdRoute: typeof PortfolioIdRoute
  AuthenticatedPortfolioIdAttributionRoute: typeof AuthenticatedPortfolioIdAttributionRoute
  ApiPublicHooksDailyRunRoute: typeof ApiPublicHooksDailyRunRoute
  ApiPublicHooksHourlyRunRoute: typeof ApiPublicHooksHourlyRunRoute
  ApiPublicHooksLiveReconcileRoute: typeof ApiPublicHooksLiveReconcileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$id': {
      id: '/portfolio/$id'
      path: '/portfolio/$id'
      fullPath: '/portfolio/$id'
      preLoaderRoute: typeof PortfolioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/long-horizon/$id': {
      id: '/long-horizon/$id'
      path: '/long-horizon/$id'
      fullPath: '/long-horizon/$id'
      preLoaderRoute: typeof LongHorizonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/live-reconcile': {
      id: '/api/public/hooks/live-reconcile'
      path: '/api/public/hooks/live-reconcile'
      fullPath: '/api/public/hooks/live-reconcile'
      preLoaderRoute: typeof ApiPublicHooksLiveReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/hourly-run': {
      id: '/api/public/hooks/hourly-run'
      path: '/api/public/hooks/hourly-run'
      fullPath: '/api/public/hooks/hourly-run'
      preLoaderRoute: typeof ApiPublicHooksHourlyRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-run': {
      id: '/api/public/hooks/daily-run'
      path: '/api/public/hooks/daily-run'
      fullPath: '/api/public/hooks/daily-run'
      preLoaderRoute: typeof ApiPublicHooksDailyRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portfolio/$id/attribution': {
      id: '/_authenticated/portfolio/$id/attribution'
      path: '/portfolio/$id/attribution'
      fullPath: '/portfolio/$id/attribution'
      preLoaderRoute: typeof AuthenticatedPortfolioIdAttributionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  GetStartedRoute: GetStartedRoute,
  LongHorizonIdRoute: LongHorizonIdRoute,
  PortfolioIdRoute: PortfolioIdRoute,
  AuthenticatedPortfolioIdAttributionRoute:
    AuthenticatedPortfolioIdAttributionRoute,
  ApiPublicHooksDailyRunRoute: ApiPublicHooksDailyRunRoute,
  ApiPublicHooksHourlyRunRoute: ApiPublicHooksHourlyRunRoute,
  ApiPublicHooksLiveReconcileRoute: ApiPublicHooksLiveReconcileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
