/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as SpilloverRouteImport } from './routes/spillover'
import { Route as SimulationReportRouteImport } from './routes/simulation-report'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SaxoStatusRouteImport } from './routes/saxo-status'
import { Route as SaxoReconnectRouteImport } from './routes/saxo-reconnect'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as HedgeFallbacksRouteImport } from './routes/hedge-fallbacks'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as DailyReportRouteImport } from './routes/daily-report'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as BrokerBlocksRouteImport } from './routes/broker-blocks'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalkForwardIdRouteImport } from './routes/walk-forward.$id'
import { Route as PortfolioIdRouteImport } from './routes/portfolio.$id'
import { Route as MarketSymbolRouteImport } from './routes/market.$symbol'
import { Route as LongHorizonIdRouteImport } from './routes/long-horizon.$id'
import { Route as PortfolioIdSummaryRouteImport } from './routes/portfolio.$id.summary'
import { Route as PortfolioIdSmaReportRouteImport } from './routes/portfolio.$id.sma-report'
import { Route as PortfolioIdReportRouteImport } from './routes/portfolio.$id.report'
import { Route as PortfolioIdOptimizerRouteImport } from './routes/portfolio.$id.optimizer'
import { Route as PortfolioIdFxRiskRouteImport } from './routes/portfolio.$id.fx-risk'
import { Route as PortfolioIdAttributionRouteImport } from './routes/portfolio.$id.attribution'
import { Route as PortfolioIdAnalyticsRouteImport } from './routes/portfolio.$id.analytics'
import { Route as ApiPublicSetupScanCronRouteImport } from './routes/api/public/setup-scan-cron'
import { Route as ApiPublicNewsPreviewRouteImport } from './routes/api/public/news-preview'
import { Route as ApiPublicAlgoRegimeAutotuneCronRouteImport } from './routes/api/public/algo-regime-autotune-cron'
import { Route as ApiBrokerBlocksClearRouteImport } from './routes/api/broker-blocks/clear'
import { Route as ApiPublicSaxoCallbackRouteImport } from './routes/api/public/saxo/callback'
import { Route as ApiPublicHooksValuationDriftRouteImport } from './routes/api/public/hooks/valuation-drift'
import { Route as ApiPublicHooksTranslationRefreshRouteImport } from './routes/api/public/hooks/translation-refresh'
import { Route as ApiPublicHooksTickerWatchRouteImport } from './routes/api/public/hooks/ticker-watch'
import { Route as ApiPublicHooksSaxoRefreshRouteImport } from './routes/api/public/hooks/saxo-refresh'
import { Route as ApiPublicHooksSaxoAccountKeyAuditRouteImport } from './routes/api/public/hooks/saxo-account-key-audit'
import { Route as ApiPublicHooksOrphanOrderSweepRouteImport } from './routes/api/public/hooks/orphan-order-sweep'
import { Route as ApiPublicHooksNewsRefreshRouteImport } from './routes/api/public/hooks/news-refresh'
import { Route as ApiPublicHooksNewsBackfillRouteImport } from './routes/api/public/hooks/news-backfill'
import { Route as ApiPublicHooksMarketOpenAlertsRouteImport } from './routes/api/public/hooks/market-open-alerts'
import { Route as ApiPublicHooksLiveReconcileRouteImport } from './routes/api/public/hooks/live-reconcile'
import { Route as ApiPublicHooksInsiderScanRouteImport } from './routes/api/public/hooks/insider-scan'
import { Route as ApiPublicHooksHourlyRunRouteImport } from './routes/api/public/hooks/hourly-run'
import { Route as ApiPublicHooksDailySummaryRouteImport } from './routes/api/public/hooks/daily-summary'
import { Route as ApiPublicHooksDailyRunRouteImport } from './routes/api/public/hooks/daily-run'
import { Route as ApiPublicHooksCreditBudgetCheckRouteImport } from './routes/api/public/hooks/credit-budget-check'
import { Route as ApiPublicHooksCorporateActionDeadlinesRouteImport } from './routes/api/public/hooks/corporate-action-deadlines'
import { Route as ApiPublicHooksBreakoutExpectancyRouteImport } from './routes/api/public/hooks/breakout-expectancy'
import { Route as ApiPublicHooksBatchRetrainRouteImport } from './routes/api/public/hooks/batch-retrain'
import { Route as ApiPublicHooksBackfillIntradayEquityRouteImport } from './routes/api/public/hooks/backfill-intraday-equity'
import { Route as ApiPublicHooksBackfillDailyEquityChangesRouteImport } from './routes/api/public/hooks/backfill-daily-equity-changes'
import { Route as ApiPublicHooksAiGatewayHealthRouteImport } from './routes/api/public/hooks/ai-gateway-health'

const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const SpilloverRoute = SpilloverRouteImport.update({
  id: '/spillover',
  path: '/spillover',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationReportRoute = SimulationReportRouteImport.update({
  id: '/simulation-report',
  path: '/simulation-report',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SaxoStatusRoute = SaxoStatusRouteImport.update({
  id: '/saxo-status',
  path: '/saxo-status',
  getParentRoute: () => rootRouteImport,
} as any)
const SaxoReconnectRoute = SaxoReconnectRouteImport.update({
  id: '/saxo-reconnect',
  path: '/saxo-reconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const HedgeFallbacksRoute = HedgeFallbacksRouteImport.update({
  id: '/hedge-fallbacks',
  path: '/hedge-fallbacks',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyReportRoute = DailyReportRouteImport.update({
  id: '/daily-report',
  path: '/daily-report',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokerBlocksRoute = BrokerBlocksRouteImport.update({
  id: '/broker-blocks',
  path: '/broker-blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalkForwardIdRoute = WalkForwardIdRouteImport.update({
  id: '/walk-forward/$id',
  path: '/walk-forward/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIdRoute = PortfolioIdRouteImport.update({
  id: '/portfolio/$id',
  path: '/portfolio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketSymbolRoute = MarketSymbolRouteImport.update({
  id: '/market/$symbol',
  path: '/market/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const LongHorizonIdRoute = LongHorizonIdRouteImport.update({
  id: '/long-horizon/$id',
  path: '/long-horizon/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIdSummaryRoute = PortfolioIdSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => PortfolioIdRoute,
} as any)
const PortfolioIdSmaReportRoute = PortfolioIdSmaReportRouteImport.update({
  id: '/sma-report',
  path: '/sma-report',
  getParentRoute: () => PortfolioIdRoute,
} as any)
const PortfolioIdReportRoute = PortfolioIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => PortfolioIdRoute,
} as any)
const PortfolioIdOptimizerRoute = PortfolioIdOptimizerRouteImport.update({
  id: '/optimizer',
  path: '/optimizer',
  getParentRoute: () => PortfolioIdRoute,
} as any)
const PortfolioIdFxRiskRoute = PortfolioIdFxRiskRouteImport.update({
  id: '/fx-risk',
  path: '/fx-risk',
  getParentRoute: () => PortfolioIdRoute,
} as any)
const PortfolioIdAttributionRoute = PortfolioIdAttributionRouteImport.update({
  id: '/attribution',
  path: '/attribution',
  getParentRoute: () => PortfolioIdRoute,
} as any)
const PortfolioIdAnalyticsRoute = PortfolioIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PortfolioIdRoute,
} as any)
const ApiPublicSetupScanCronRoute = ApiPublicSetupScanCronRouteImport.update({
  id: '/api/public/setup-scan-cron',
  path: '/api/public/setup-scan-cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsPreviewRoute = ApiPublicNewsPreviewRouteImport.update({
  id: '/api/public/news-preview',
  path: '/api/public/news-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAlgoRegimeAutotuneCronRoute =
  ApiPublicAlgoRegimeAutotuneCronRouteImport.update({
    id: '/api/public/algo-regime-autotune-cron',
    path: '/api/public/algo-regime-autotune-cron',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBrokerBlocksClearRoute = ApiBrokerBlocksClearRouteImport.update({
  id: '/api/broker-blocks/clear',
  path: '/api/broker-blocks/clear',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSaxoCallbackRoute = ApiPublicSaxoCallbackRouteImport.update({
  id: '/api/public/saxo/callback',
  path: '/api/public/saxo/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksValuationDriftRoute =
  ApiPublicHooksValuationDriftRouteImport.update({
    id: '/api/public/hooks/valuation-drift',
    path: '/api/public/hooks/valuation-drift',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTranslationRefreshRoute =
  ApiPublicHooksTranslationRefreshRouteImport.update({
    id: '/api/public/hooks/translation-refresh',
    path: '/api/public/hooks/translation-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTickerWatchRoute =
  ApiPublicHooksTickerWatchRouteImport.update({
    id: '/api/public/hooks/ticker-watch',
    path: '/api/public/hooks/ticker-watch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSaxoRefreshRoute =
  ApiPublicHooksSaxoRefreshRouteImport.update({
    id: '/api/public/hooks/saxo-refresh',
    path: '/api/public/hooks/saxo-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSaxoAccountKeyAuditRoute =
  ApiPublicHooksSaxoAccountKeyAuditRouteImport.update({
    id: '/api/public/hooks/saxo-account-key-audit',
    path: '/api/public/hooks/saxo-account-key-audit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksOrphanOrderSweepRoute =
  ApiPublicHooksOrphanOrderSweepRouteImport.update({
    id: '/api/public/hooks/orphan-order-sweep',
    path: '/api/public/hooks/orphan-order-sweep',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNewsRefreshRoute =
  ApiPublicHooksNewsRefreshRouteImport.update({
    id: '/api/public/hooks/news-refresh',
    path: '/api/public/hooks/news-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNewsBackfillRoute =
  ApiPublicHooksNewsBackfillRouteImport.update({
    id: '/api/public/hooks/news-backfill',
    path: '/api/public/hooks/news-backfill',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMarketOpenAlertsRoute =
  ApiPublicHooksMarketOpenAlertsRouteImport.update({
    id: '/api/public/hooks/market-open-alerts',
    path: '/api/public/hooks/market-open-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLiveReconcileRoute =
  ApiPublicHooksLiveReconcileRouteImport.update({
    id: '/api/public/hooks/live-reconcile',
    path: '/api/public/hooks/live-reconcile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksInsiderScanRoute =
  ApiPublicHooksInsiderScanRouteImport.update({
    id: '/api/public/hooks/insider-scan',
    path: '/api/public/hooks/insider-scan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksHourlyRunRoute = ApiPublicHooksHourlyRunRouteImport.update({
  id: '/api/public/hooks/hourly-run',
  path: '/api/public/hooks/hourly-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailySummaryRoute =
  ApiPublicHooksDailySummaryRouteImport.update({
    id: '/api/public/hooks/daily-summary',
    path: '/api/public/hooks/daily-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyRunRoute = ApiPublicHooksDailyRunRouteImport.update({
  id: '/api/public/hooks/daily-run',
  path: '/api/public/hooks/daily-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCreditBudgetCheckRoute =
  ApiPublicHooksCreditBudgetCheckRouteImport.update({
    id: '/api/public/hooks/credit-budget-check',
    path: '/api/public/hooks/credit-budget-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCorporateActionDeadlinesRoute =
  ApiPublicHooksCorporateActionDeadlinesRouteImport.update({
    id: '/api/public/hooks/corporate-action-deadlines',
    path: '/api/public/hooks/corporate-action-deadlines',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBreakoutExpectancyRoute =
  ApiPublicHooksBreakoutExpectancyRouteImport.update({
    id: '/api/public/hooks/breakout-expectancy',
    path: '/api/public/hooks/breakout-expectancy',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBatchRetrainRoute =
  ApiPublicHooksBatchRetrainRouteImport.update({
    id: '/api/public/hooks/batch-retrain',
    path: '/api/public/hooks/batch-retrain',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBackfillIntradayEquityRoute =
  ApiPublicHooksBackfillIntradayEquityRouteImport.update({
    id: '/api/public/hooks/backfill-intraday-equity',
    path: '/api/public/hooks/backfill-intraday-equity',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBackfillDailyEquityChangesRoute =
  ApiPublicHooksBackfillDailyEquityChangesRouteImport.update({
    id: '/api/public/hooks/backfill-daily-equity-changes',
    path: '/api/public/hooks/backfill-daily-equity-changes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAiGatewayHealthRoute =
  ApiPublicHooksAiGatewayHealthRouteImport.update({
    id: '/api/public/hooks/ai-gateway-health',
    path: '/api/public/hooks/ai-gateway-health',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/broker-blocks': typeof BrokerBlocksRoute
  '/compare': typeof CompareRoute
  '/daily-report': typeof DailyReportRoute
  '/get-started': typeof GetStartedRoute
  '/hedge-fallbacks': typeof HedgeFallbacksRoute
  '/learn': typeof LearnRoute
  '/markets': typeof MarketsRoute
  '/research': typeof ResearchRoute
  '/saxo-reconnect': typeof SaxoReconnectRoute
  '/saxo-status': typeof SaxoStatusRoute
  '/settings': typeof SettingsRoute
  '/simulation-report': typeof SimulationReportRoute
  '/spillover': typeof SpilloverRoute
  '/trades': typeof TradesRoute
  '/long-horizon/$id': typeof LongHorizonIdRoute
  '/market/$symbol': typeof MarketSymbolRoute
  '/portfolio/$id': typeof PortfolioIdRouteWithChildren
  '/walk-forward/$id': typeof WalkForwardIdRoute
  '/api/broker-blocks/clear': typeof ApiBrokerBlocksClearRoute
  '/api/public/algo-regime-autotune-cron': typeof ApiPublicAlgoRegimeAutotuneCronRoute
  '/api/public/news-preview': typeof ApiPublicNewsPreviewRoute
  '/api/public/setup-scan-cron': typeof ApiPublicSetupScanCronRoute
  '/portfolio/$id/analytics': typeof PortfolioIdAnalyticsRoute
  '/portfolio/$id/attribution': typeof PortfolioIdAttributionRoute
  '/portfolio/$id/fx-risk': typeof PortfolioIdFxRiskRoute
  '/portfolio/$id/optimizer': typeof PortfolioIdOptimizerRoute
  '/portfolio/$id/report': typeof PortfolioIdReportRoute
  '/portfolio/$id/sma-report': typeof PortfolioIdSmaReportRoute
  '/portfolio/$id/summary': typeof PortfolioIdSummaryRoute
  '/api/public/hooks/ai-gateway-health': typeof ApiPublicHooksAiGatewayHealthRoute
  '/api/public/hooks/backfill-daily-equity-changes': typeof ApiPublicHooksBackfillDailyEquityChangesRoute
  '/api/public/hooks/backfill-intraday-equity': typeof ApiPublicHooksBackfillIntradayEquityRoute
  '/api/public/hooks/batch-retrain': typeof ApiPublicHooksBatchRetrainRoute
  '/api/public/hooks/breakout-expectancy': typeof ApiPublicHooksBreakoutExpectancyRoute
  '/api/public/hooks/corporate-action-deadlines': typeof ApiPublicHooksCorporateActionDeadlinesRoute
  '/api/public/hooks/credit-budget-check': typeof ApiPublicHooksCreditBudgetCheckRoute
  '/api/public/hooks/daily-run': typeof ApiPublicHooksDailyRunRoute
  '/api/public/hooks/daily-summary': typeof ApiPublicHooksDailySummaryRoute
  '/api/public/hooks/hourly-run': typeof ApiPublicHooksHourlyRunRoute
  '/api/public/hooks/insider-scan': typeof ApiPublicHooksInsiderScanRoute
  '/api/public/hooks/live-reconcile': typeof ApiPublicHooksLiveReconcileRoute
  '/api/public/hooks/market-open-alerts': typeof ApiPublicHooksMarketOpenAlertsRoute
  '/api/public/hooks/news-backfill': typeof ApiPublicHooksNewsBackfillRoute
  '/api/public/hooks/news-refresh': typeof ApiPublicHooksNewsRefreshRoute
  '/api/public/hooks/orphan-order-sweep': typeof ApiPublicHooksOrphanOrderSweepRoute
  '/api/public/hooks/saxo-account-key-audit': typeof ApiPublicHooksSaxoAccountKeyAuditRoute
  '/api/public/hooks/saxo-refresh': typeof ApiPublicHooksSaxoRefreshRoute
  '/api/public/hooks/ticker-watch': typeof ApiPublicHooksTickerWatchRoute
  '/api/public/hooks/translation-refresh': typeof ApiPublicHooksTranslationRefreshRoute
  '/api/public/hooks/valuation-drift': typeof ApiPublicHooksValuationDriftRoute
  '/api/public/saxo/callback': typeof ApiPublicSaxoCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/broker-blocks': typeof BrokerBlocksRoute
  '/compare': typeof CompareRoute
  '/daily-report': typeof DailyReportRoute
  '/get-started': typeof GetStartedRoute
  '/hedge-fallbacks': typeof HedgeFallbacksRoute
  '/learn': typeof LearnRoute
  '/markets': typeof MarketsRoute
  '/research': typeof ResearchRoute
  '/saxo-reconnect': typeof SaxoReconnectRoute
  '/saxo-status': typeof SaxoStatusRoute
  '/settings': typeof SettingsRoute
  '/simulation-report': typeof SimulationReportRoute
  '/spillover': typeof SpilloverRoute
  '/trades': typeof TradesRoute
  '/long-horizon/$id': typeof LongHorizonIdRoute
  '/market/$symbol': typeof MarketSymbolRoute
  '/portfolio/$id': typeof PortfolioIdRouteWithChildren
  '/walk-forward/$id': typeof WalkForwardIdRoute
  '/api/broker-blocks/clear': typeof ApiBrokerBlocksClearRoute
  '/api/public/algo-regime-autotune-cron': typeof ApiPublicAlgoRegimeAutotuneCronRoute
  '/api/public/news-preview': typeof ApiPublicNewsPreviewRoute
  '/api/public/setup-scan-cron': typeof ApiPublicSetupScanCronRoute
  '/portfolio/$id/analytics': typeof PortfolioIdAnalyticsRoute
  '/portfolio/$id/attribution': typeof PortfolioIdAttributionRoute
  '/portfolio/$id/fx-risk': typeof PortfolioIdFxRiskRoute
  '/portfolio/$id/optimizer': typeof PortfolioIdOptimizerRoute
  '/portfolio/$id/report': typeof PortfolioIdReportRoute
  '/portfolio/$id/sma-report': typeof PortfolioIdSmaReportRoute
  '/portfolio/$id/summary': typeof PortfolioIdSummaryRoute
  '/api/public/hooks/ai-gateway-health': typeof ApiPublicHooksAiGatewayHealthRoute
  '/api/public/hooks/backfill-daily-equity-changes': typeof ApiPublicHooksBackfillDailyEquityChangesRoute
  '/api/public/hooks/backfill-intraday-equity': typeof ApiPublicHooksBackfillIntradayEquityRoute
  '/api/public/hooks/batch-retrain': typeof ApiPublicHooksBatchRetrainRoute
  '/api/public/hooks/breakout-expectancy': typeof ApiPublicHooksBreakoutExpectancyRoute
  '/api/public/hooks/corporate-action-deadlines': typeof ApiPublicHooksCorporateActionDeadlinesRoute
  '/api/public/hooks/credit-budget-check': typeof ApiPublicHooksCreditBudgetCheckRoute
  '/api/public/hooks/daily-run': typeof ApiPublicHooksDailyRunRoute
  '/api/public/hooks/daily-summary': typeof ApiPublicHooksDailySummaryRoute
  '/api/public/hooks/hourly-run': typeof ApiPublicHooksHourlyRunRoute
  '/api/public/hooks/insider-scan': typeof ApiPublicHooksInsiderScanRoute
  '/api/public/hooks/live-reconcile': typeof ApiPublicHooksLiveReconcileRoute
  '/api/public/hooks/market-open-alerts': typeof ApiPublicHooksMarketOpenAlertsRoute
  '/api/public/hooks/news-backfill': typeof ApiPublicHooksNewsBackfillRoute
  '/api/public/hooks/news-refresh': typeof ApiPublicHooksNewsRefreshRoute
  '/api/public/hooks/orphan-order-sweep': typeof ApiPublicHooksOrphanOrderSweepRoute
  '/api/public/hooks/saxo-account-key-audit': typeof ApiPublicHooksSaxoAccountKeyAuditRoute
  '/api/public/hooks/saxo-refresh': typeof ApiPublicHooksSaxoRefreshRoute
  '/api/public/hooks/ticker-watch': typeof ApiPublicHooksTickerWatchRoute
  '/api/public/hooks/translation-refresh': typeof ApiPublicHooksTranslationRefreshRoute
  '/api/public/hooks/valuation-drift': typeof ApiPublicHooksValuationDriftRoute
  '/api/public/saxo/callback': typeof ApiPublicSaxoCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/broker-blocks': typeof BrokerBlocksRoute
  '/compare': typeof CompareRoute
  '/daily-report': typeof DailyReportRoute
  '/get-started': typeof GetStartedRoute
  '/hedge-fallbacks': typeof HedgeFallbacksRoute
  '/learn': typeof LearnRoute
  '/markets': typeof MarketsRoute
  '/research': typeof ResearchRoute
  '/saxo-reconnect': typeof SaxoReconnectRoute
  '/saxo-status': typeof SaxoStatusRoute
  '/settings': typeof SettingsRoute
  '/simulation-report': typeof SimulationReportRoute
  '/spillover': typeof SpilloverRoute
  '/trades': typeof TradesRoute
  '/long-horizon/$id': typeof LongHorizonIdRoute
  '/market/$symbol': typeof MarketSymbolRoute
  '/portfolio/$id': typeof PortfolioIdRouteWithChildren
  '/walk-forward/$id': typeof WalkForwardIdRoute
  '/api/broker-blocks/clear': typeof ApiBrokerBlocksClearRoute
  '/api/public/algo-regime-autotune-cron': typeof ApiPublicAlgoRegimeAutotuneCronRoute
  '/api/public/news-preview': typeof ApiPublicNewsPreviewRoute
  '/api/public/setup-scan-cron': typeof ApiPublicSetupScanCronRoute
  '/portfolio/$id/analytics': typeof PortfolioIdAnalyticsRoute
  '/portfolio/$id/attribution': typeof PortfolioIdAttributionRoute
  '/portfolio/$id/fx-risk': typeof PortfolioIdFxRiskRoute
  '/portfolio/$id/optimizer': typeof PortfolioIdOptimizerRoute
  '/portfolio/$id/report': typeof PortfolioIdReportRoute
  '/portfolio/$id/sma-report': typeof PortfolioIdSmaReportRoute
  '/portfolio/$id/summary': typeof PortfolioIdSummaryRoute
  '/api/public/hooks/ai-gateway-health': typeof ApiPublicHooksAiGatewayHealthRoute
  '/api/public/hooks/backfill-daily-equity-changes': typeof ApiPublicHooksBackfillDailyEquityChangesRoute
  '/api/public/hooks/backfill-intraday-equity': typeof ApiPublicHooksBackfillIntradayEquityRoute
  '/api/public/hooks/batch-retrain': typeof ApiPublicHooksBatchRetrainRoute
  '/api/public/hooks/breakout-expectancy': typeof ApiPublicHooksBreakoutExpectancyRoute
  '/api/public/hooks/corporate-action-deadlines': typeof ApiPublicHooksCorporateActionDeadlinesRoute
  '/api/public/hooks/credit-budget-check': typeof ApiPublicHooksCreditBudgetCheckRoute
  '/api/public/hooks/daily-run': typeof ApiPublicHooksDailyRunRoute
  '/api/public/hooks/daily-summary': typeof ApiPublicHooksDailySummaryRoute
  '/api/public/hooks/hourly-run': typeof ApiPublicHooksHourlyRunRoute
  '/api/public/hooks/insider-scan': typeof ApiPublicHooksInsiderScanRoute
  '/api/public/hooks/live-reconcile': typeof ApiPublicHooksLiveReconcileRoute
  '/api/public/hooks/market-open-alerts': typeof ApiPublicHooksMarketOpenAlertsRoute
  '/api/public/hooks/news-backfill': typeof ApiPublicHooksNewsBackfillRoute
  '/api/public/hooks/news-refresh': typeof ApiPublicHooksNewsRefreshRoute
  '/api/public/hooks/orphan-order-sweep': typeof ApiPublicHooksOrphanOrderSweepRoute
  '/api/public/hooks/saxo-account-key-audit': typeof ApiPublicHooksSaxoAccountKeyAuditRoute
  '/api/public/hooks/saxo-refresh': typeof ApiPublicHooksSaxoRefreshRoute
  '/api/public/hooks/ticker-watch': typeof ApiPublicHooksTickerWatchRoute
  '/api/public/hooks/translation-refresh': typeof ApiPublicHooksTranslationRefreshRoute
  '/api/public/hooks/valuation-drift': typeof ApiPublicHooksValuationDriftRoute
  '/api/public/saxo/callback': typeof ApiPublicSaxoCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/broker-blocks'
    | '/compare'
    | '/daily-report'
    | '/get-started'
    | '/hedge-fallbacks'
    | '/learn'
    | '/markets'
    | '/research'
    | '/saxo-reconnect'
    | '/saxo-status'
    | '/settings'
    | '/simulation-report'
    | '/spillover'
    | '/trades'
    | '/long-horizon/$id'
    | '/market/$symbol'
    | '/portfolio/$id'
    | '/walk-forward/$id'
    | '/api/broker-blocks/clear'
    | '/api/public/algo-regime-autotune-cron'
    | '/api/public/news-preview'
    | '/api/public/setup-scan-cron'
    | '/portfolio/$id/analytics'
    | '/portfolio/$id/attribution'
    | '/portfolio/$id/fx-risk'
    | '/portfolio/$id/optimizer'
    | '/portfolio/$id/report'
    | '/portfolio/$id/sma-report'
    | '/portfolio/$id/summary'
    | '/api/public/hooks/ai-gateway-health'
    | '/api/public/hooks/backfill-daily-equity-changes'
    | '/api/public/hooks/backfill-intraday-equity'
    | '/api/public/hooks/batch-retrain'
    | '/api/public/hooks/breakout-expectancy'
    | '/api/public/hooks/corporate-action-deadlines'
    | '/api/public/hooks/credit-budget-check'
    | '/api/public/hooks/daily-run'
    | '/api/public/hooks/daily-summary'
    | '/api/public/hooks/hourly-run'
    | '/api/public/hooks/insider-scan'
    | '/api/public/hooks/live-reconcile'
    | '/api/public/hooks/market-open-alerts'
    | '/api/public/hooks/news-backfill'
    | '/api/public/hooks/news-refresh'
    | '/api/public/hooks/orphan-order-sweep'
    | '/api/public/hooks/saxo-account-key-audit'
    | '/api/public/hooks/saxo-refresh'
    | '/api/public/hooks/ticker-watch'
    | '/api/public/hooks/translation-refresh'
    | '/api/public/hooks/valuation-drift'
    | '/api/public/saxo/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/broker-blocks'
    | '/compare'
    | '/daily-report'
    | '/get-started'
    | '/hedge-fallbacks'
    | '/learn'
    | '/markets'
    | '/research'
    | '/saxo-reconnect'
    | '/saxo-status'
    | '/settings'
    | '/simulation-report'
    | '/spillover'
    | '/trades'
    | '/long-horizon/$id'
    | '/market/$symbol'
    | '/portfolio/$id'
    | '/walk-forward/$id'
    | '/api/broker-blocks/clear'
    | '/api/public/algo-regime-autotune-cron'
    | '/api/public/news-preview'
    | '/api/public/setup-scan-cron'
    | '/portfolio/$id/analytics'
    | '/portfolio/$id/attribution'
    | '/portfolio/$id/fx-risk'
    | '/portfolio/$id/optimizer'
    | '/portfolio/$id/report'
    | '/portfolio/$id/sma-report'
    | '/portfolio/$id/summary'
    | '/api/public/hooks/ai-gateway-health'
    | '/api/public/hooks/backfill-daily-equity-changes'
    | '/api/public/hooks/backfill-intraday-equity'
    | '/api/public/hooks/batch-retrain'
    | '/api/public/hooks/breakout-expectancy'
    | '/api/public/hooks/corporate-action-deadlines'
    | '/api/public/hooks/credit-budget-check'
    | '/api/public/hooks/daily-run'
    | '/api/public/hooks/daily-summary'
    | '/api/public/hooks/hourly-run'
    | '/api/public/hooks/insider-scan'
    | '/api/public/hooks/live-reconcile'
    | '/api/public/hooks/market-open-alerts'
    | '/api/public/hooks/news-backfill'
    | '/api/public/hooks/news-refresh'
    | '/api/public/hooks/orphan-order-sweep'
    | '/api/public/hooks/saxo-account-key-audit'
    | '/api/public/hooks/saxo-refresh'
    | '/api/public/hooks/ticker-watch'
    | '/api/public/hooks/translation-refresh'
    | '/api/public/hooks/valuation-drift'
    | '/api/public/saxo/callback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/broker-blocks'
    | '/compare'
    | '/daily-report'
    | '/get-started'
    | '/hedge-fallbacks'
    | '/learn'
    | '/markets'
    | '/research'
    | '/saxo-reconnect'
    | '/saxo-status'
    | '/settings'
    | '/simulation-report'
    | '/spillover'
    | '/trades'
    | '/long-horizon/$id'
    | '/market/$symbol'
    | '/portfolio/$id'
    | '/walk-forward/$id'
    | '/api/broker-blocks/clear'
    | '/api/public/algo-regime-autotune-cron'
    | '/api/public/news-preview'
    | '/api/public/setup-scan-cron'
    | '/portfolio/$id/analytics'
    | '/portfolio/$id/attribution'
    | '/portfolio/$id/fx-risk'
    | '/portfolio/$id/optimizer'
    | '/portfolio/$id/report'
    | '/portfolio/$id/sma-report'
    | '/portfolio/$id/summary'
    | '/api/public/hooks/ai-gateway-health'
    | '/api/public/hooks/backfill-daily-equity-changes'
    | '/api/public/hooks/backfill-intraday-equity'
    | '/api/public/hooks/batch-retrain'
    | '/api/public/hooks/breakout-expectancy'
    | '/api/public/hooks/corporate-action-deadlines'
    | '/api/public/hooks/credit-budget-check'
    | '/api/public/hooks/daily-run'
    | '/api/public/hooks/daily-summary'
    | '/api/public/hooks/hourly-run'
    | '/api/public/hooks/insider-scan'
    | '/api/public/hooks/live-reconcile'
    | '/api/public/hooks/market-open-alerts'
    | '/api/public/hooks/news-backfill'
    | '/api/public/hooks/news-refresh'
    | '/api/public/hooks/orphan-order-sweep'
    | '/api/public/hooks/saxo-account-key-audit'
    | '/api/public/hooks/saxo-refresh'
    | '/api/public/hooks/ticker-watch'
    | '/api/public/hooks/translation-refresh'
    | '/api/public/hooks/valuation-drift'
    | '/api/public/saxo/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BrokerBlocksRoute: typeof BrokerBlocksRoute
  CompareRoute: typeof CompareRoute
  DailyReportRoute: typeof DailyReportRoute
  GetStartedRoute: typeof GetStartedRoute
  HedgeFallbacksRoute: typeof HedgeFallbacksRoute
  LearnRoute: typeof LearnRoute
  MarketsRoute: typeof MarketsRoute
  ResearchRoute: typeof ResearchRoute
  SaxoReconnectRoute: typeof SaxoReconnectRoute
  SaxoStatusRoute: typeof SaxoStatusRoute
  SettingsRoute: typeof SettingsRoute
  SimulationReportRoute: typeof SimulationReportRoute
  SpilloverRoute: typeof SpilloverRoute
  TradesRoute: typeof TradesRoute
  LongHorizonIdRoute: typeof LongHorizonIdRoute
  MarketSymbolRoute: typeof MarketSymbolRoute
  PortfolioIdRoute: typeof PortfolioIdRouteWithChildren
  WalkForwardIdRoute: typeof WalkForwardIdRoute
  ApiBrokerBlocksClearRoute: typeof ApiBrokerBlocksClearRoute
  ApiPublicAlgoRegimeAutotuneCronRoute: typeof ApiPublicAlgoRegimeAutotuneCronRoute
  ApiPublicNewsPreviewRoute: typeof ApiPublicNewsPreviewRoute
  ApiPublicSetupScanCronRoute: typeof ApiPublicSetupScanCronRoute
  ApiPublicHooksAiGatewayHealthRoute: typeof ApiPublicHooksAiGatewayHealthRoute
  ApiPublicHooksBackfillDailyEquityChangesRoute: typeof ApiPublicHooksBackfillDailyEquityChangesRoute
  ApiPublicHooksBackfillIntradayEquityRoute: typeof ApiPublicHooksBackfillIntradayEquityRoute
  ApiPublicHooksBatchRetrainRoute: typeof ApiPublicHooksBatchRetrainRoute
  ApiPublicHooksBreakoutExpectancyRoute: typeof ApiPublicHooksBreakoutExpectancyRoute
  ApiPublicHooksCorporateActionDeadlinesRoute: typeof ApiPublicHooksCorporateActionDeadlinesRoute
  ApiPublicHooksCreditBudgetCheckRoute: typeof ApiPublicHooksCreditBudgetCheckRoute
  ApiPublicHooksDailyRunRoute: typeof ApiPublicHooksDailyRunRoute
  ApiPublicHooksDailySummaryRoute: typeof ApiPublicHooksDailySummaryRoute
  ApiPublicHooksHourlyRunRoute: typeof ApiPublicHooksHourlyRunRoute
  ApiPublicHooksInsiderScanRoute: typeof ApiPublicHooksInsiderScanRoute
  ApiPublicHooksLiveReconcileRoute: typeof ApiPublicHooksLiveReconcileRoute
  ApiPublicHooksMarketOpenAlertsRoute: typeof ApiPublicHooksMarketOpenAlertsRoute
  ApiPublicHooksNewsBackfillRoute: typeof ApiPublicHooksNewsBackfillRoute
  ApiPublicHooksNewsRefreshRoute: typeof ApiPublicHooksNewsRefreshRoute
  ApiPublicHooksOrphanOrderSweepRoute: typeof ApiPublicHooksOrphanOrderSweepRoute
  ApiPublicHooksSaxoAccountKeyAuditRoute: typeof ApiPublicHooksSaxoAccountKeyAuditRoute
  ApiPublicHooksSaxoRefreshRoute: typeof ApiPublicHooksSaxoRefreshRoute
  ApiPublicHooksTickerWatchRoute: typeof ApiPublicHooksTickerWatchRoute
  ApiPublicHooksTranslationRefreshRoute: typeof ApiPublicHooksTranslationRefreshRoute
  ApiPublicHooksValuationDriftRoute: typeof ApiPublicHooksValuationDriftRoute
  ApiPublicSaxoCallbackRoute: typeof ApiPublicSaxoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spillover': {
      id: '/spillover'
      path: '/spillover'
      fullPath: '/spillover'
      preLoaderRoute: typeof SpilloverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation-report': {
      id: '/simulation-report'
      path: '/simulation-report'
      fullPath: '/simulation-report'
      preLoaderRoute: typeof SimulationReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saxo-status': {
      id: '/saxo-status'
      path: '/saxo-status'
      fullPath: '/saxo-status'
      preLoaderRoute: typeof SaxoStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saxo-reconnect': {
      id: '/saxo-reconnect'
      path: '/saxo-reconnect'
      fullPath: '/saxo-reconnect'
      preLoaderRoute: typeof SaxoReconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hedge-fallbacks': {
      id: '/hedge-fallbacks'
      path: '/hedge-fallbacks'
      fullPath: '/hedge-fallbacks'
      preLoaderRoute: typeof HedgeFallbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-report': {
      id: '/daily-report'
      path: '/daily-report'
      fullPath: '/daily-report'
      preLoaderRoute: typeof DailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broker-blocks': {
      id: '/broker-blocks'
      path: '/broker-blocks'
      fullPath: '/broker-blocks'
      preLoaderRoute: typeof BrokerBlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walk-forward/$id': {
      id: '/walk-forward/$id'
      path: '/walk-forward/$id'
      fullPath: '/walk-forward/$id'
      preLoaderRoute: typeof WalkForwardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$id': {
      id: '/portfolio/$id'
      path: '/portfolio/$id'
      fullPath: '/portfolio/$id'
      preLoaderRoute: typeof PortfolioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$symbol': {
      id: '/market/$symbol'
      path: '/market/$symbol'
      fullPath: '/market/$symbol'
      preLoaderRoute: typeof MarketSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/long-horizon/$id': {
      id: '/long-horizon/$id'
      path: '/long-horizon/$id'
      fullPath: '/long-horizon/$id'
      preLoaderRoute: typeof LongHorizonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$id/summary': {
      id: '/portfolio/$id/summary'
      path: '/summary'
      fullPath: '/portfolio/$id/summary'
      preLoaderRoute: typeof PortfolioIdSummaryRouteImport
      parentRoute: typeof PortfolioIdRoute
    }
    '/portfolio/$id/sma-report': {
      id: '/portfolio/$id/sma-report'
      path: '/sma-report'
      fullPath: '/portfolio/$id/sma-report'
      preLoaderRoute: typeof PortfolioIdSmaReportRouteImport
      parentRoute: typeof PortfolioIdRoute
    }
    '/portfolio/$id/report': {
      id: '/portfolio/$id/report'
      path: '/report'
      fullPath: '/portfolio/$id/report'
      preLoaderRoute: typeof PortfolioIdReportRouteImport
      parentRoute: typeof PortfolioIdRoute
    }
    '/portfolio/$id/optimizer': {
      id: '/portfolio/$id/optimizer'
      path: '/optimizer'
      fullPath: '/portfolio/$id/optimizer'
      preLoaderRoute: typeof PortfolioIdOptimizerRouteImport
      parentRoute: typeof PortfolioIdRoute
    }
    '/portfolio/$id/fx-risk': {
      id: '/portfolio/$id/fx-risk'
      path: '/fx-risk'
      fullPath: '/portfolio/$id/fx-risk'
      preLoaderRoute: typeof PortfolioIdFxRiskRouteImport
      parentRoute: typeof PortfolioIdRoute
    }
    '/portfolio/$id/attribution': {
      id: '/portfolio/$id/attribution'
      path: '/attribution'
      fullPath: '/portfolio/$id/attribution'
      preLoaderRoute: typeof PortfolioIdAttributionRouteImport
      parentRoute: typeof PortfolioIdRoute
    }
    '/portfolio/$id/analytics': {
      id: '/portfolio/$id/analytics'
      path: '/analytics'
      fullPath: '/portfolio/$id/analytics'
      preLoaderRoute: typeof PortfolioIdAnalyticsRouteImport
      parentRoute: typeof PortfolioIdRoute
    }
    '/api/public/setup-scan-cron': {
      id: '/api/public/setup-scan-cron'
      path: '/api/public/setup-scan-cron'
      fullPath: '/api/public/setup-scan-cron'
      preLoaderRoute: typeof ApiPublicSetupScanCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/news-preview': {
      id: '/api/public/news-preview'
      path: '/api/public/news-preview'
      fullPath: '/api/public/news-preview'
      preLoaderRoute: typeof ApiPublicNewsPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/algo-regime-autotune-cron': {
      id: '/api/public/algo-regime-autotune-cron'
      path: '/api/public/algo-regime-autotune-cron'
      fullPath: '/api/public/algo-regime-autotune-cron'
      preLoaderRoute: typeof ApiPublicAlgoRegimeAutotuneCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/broker-blocks/clear': {
      id: '/api/broker-blocks/clear'
      path: '/api/broker-blocks/clear'
      fullPath: '/api/broker-blocks/clear'
      preLoaderRoute: typeof ApiBrokerBlocksClearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/saxo/callback': {
      id: '/api/public/saxo/callback'
      path: '/api/public/saxo/callback'
      fullPath: '/api/public/saxo/callback'
      preLoaderRoute: typeof ApiPublicSaxoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/valuation-drift': {
      id: '/api/public/hooks/valuation-drift'
      path: '/api/public/hooks/valuation-drift'
      fullPath: '/api/public/hooks/valuation-drift'
      preLoaderRoute: typeof ApiPublicHooksValuationDriftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/translation-refresh': {
      id: '/api/public/hooks/translation-refresh'
      path: '/api/public/hooks/translation-refresh'
      fullPath: '/api/public/hooks/translation-refresh'
      preLoaderRoute: typeof ApiPublicHooksTranslationRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ticker-watch': {
      id: '/api/public/hooks/ticker-watch'
      path: '/api/public/hooks/ticker-watch'
      fullPath: '/api/public/hooks/ticker-watch'
      preLoaderRoute: typeof ApiPublicHooksTickerWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/saxo-refresh': {
      id: '/api/public/hooks/saxo-refresh'
      path: '/api/public/hooks/saxo-refresh'
      fullPath: '/api/public/hooks/saxo-refresh'
      preLoaderRoute: typeof ApiPublicHooksSaxoRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/saxo-account-key-audit': {
      id: '/api/public/hooks/saxo-account-key-audit'
      path: '/api/public/hooks/saxo-account-key-audit'
      fullPath: '/api/public/hooks/saxo-account-key-audit'
      preLoaderRoute: typeof ApiPublicHooksSaxoAccountKeyAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/orphan-order-sweep': {
      id: '/api/public/hooks/orphan-order-sweep'
      path: '/api/public/hooks/orphan-order-sweep'
      fullPath: '/api/public/hooks/orphan-order-sweep'
      preLoaderRoute: typeof ApiPublicHooksOrphanOrderSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/news-refresh': {
      id: '/api/public/hooks/news-refresh'
      path: '/api/public/hooks/news-refresh'
      fullPath: '/api/public/hooks/news-refresh'
      preLoaderRoute: typeof ApiPublicHooksNewsRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/news-backfill': {
      id: '/api/public/hooks/news-backfill'
      path: '/api/public/hooks/news-backfill'
      fullPath: '/api/public/hooks/news-backfill'
      preLoaderRoute: typeof ApiPublicHooksNewsBackfillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/market-open-alerts': {
      id: '/api/public/hooks/market-open-alerts'
      path: '/api/public/hooks/market-open-alerts'
      fullPath: '/api/public/hooks/market-open-alerts'
      preLoaderRoute: typeof ApiPublicHooksMarketOpenAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/live-reconcile': {
      id: '/api/public/hooks/live-reconcile'
      path: '/api/public/hooks/live-reconcile'
      fullPath: '/api/public/hooks/live-reconcile'
      preLoaderRoute: typeof ApiPublicHooksLiveReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/insider-scan': {
      id: '/api/public/hooks/insider-scan'
      path: '/api/public/hooks/insider-scan'
      fullPath: '/api/public/hooks/insider-scan'
      preLoaderRoute: typeof ApiPublicHooksInsiderScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/hourly-run': {
      id: '/api/public/hooks/hourly-run'
      path: '/api/public/hooks/hourly-run'
      fullPath: '/api/public/hooks/hourly-run'
      preLoaderRoute: typeof ApiPublicHooksHourlyRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-summary': {
      id: '/api/public/hooks/daily-summary'
      path: '/api/public/hooks/daily-summary'
      fullPath: '/api/public/hooks/daily-summary'
      preLoaderRoute: typeof ApiPublicHooksDailySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-run': {
      id: '/api/public/hooks/daily-run'
      path: '/api/public/hooks/daily-run'
      fullPath: '/api/public/hooks/daily-run'
      preLoaderRoute: typeof ApiPublicHooksDailyRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/credit-budget-check': {
      id: '/api/public/hooks/credit-budget-check'
      path: '/api/public/hooks/credit-budget-check'
      fullPath: '/api/public/hooks/credit-budget-check'
      preLoaderRoute: typeof ApiPublicHooksCreditBudgetCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/corporate-action-deadlines': {
      id: '/api/public/hooks/corporate-action-deadlines'
      path: '/api/public/hooks/corporate-action-deadlines'
      fullPath: '/api/public/hooks/corporate-action-deadlines'
      preLoaderRoute: typeof ApiPublicHooksCorporateActionDeadlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/breakout-expectancy': {
      id: '/api/public/hooks/breakout-expectancy'
      path: '/api/public/hooks/breakout-expectancy'
      fullPath: '/api/public/hooks/breakout-expectancy'
      preLoaderRoute: typeof ApiPublicHooksBreakoutExpectancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/batch-retrain': {
      id: '/api/public/hooks/batch-retrain'
      path: '/api/public/hooks/batch-retrain'
      fullPath: '/api/public/hooks/batch-retrain'
      preLoaderRoute: typeof ApiPublicHooksBatchRetrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backfill-intraday-equity': {
      id: '/api/public/hooks/backfill-intraday-equity'
      path: '/api/public/hooks/backfill-intraday-equity'
      fullPath: '/api/public/hooks/backfill-intraday-equity'
      preLoaderRoute: typeof ApiPublicHooksBackfillIntradayEquityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backfill-daily-equity-changes': {
      id: '/api/public/hooks/backfill-daily-equity-changes'
      path: '/api/public/hooks/backfill-daily-equity-changes'
      fullPath: '/api/public/hooks/backfill-daily-equity-changes'
      preLoaderRoute: typeof ApiPublicHooksBackfillDailyEquityChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ai-gateway-health': {
      id: '/api/public/hooks/ai-gateway-health'
      path: '/api/public/hooks/ai-gateway-health'
      fullPath: '/api/public/hooks/ai-gateway-health'
      preLoaderRoute: typeof ApiPublicHooksAiGatewayHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortfolioIdRouteChildren {
  PortfolioIdAnalyticsRoute: typeof PortfolioIdAnalyticsRoute
  PortfolioIdAttributionRoute: typeof PortfolioIdAttributionRoute
  PortfolioIdFxRiskRoute: typeof PortfolioIdFxRiskRoute
  PortfolioIdOptimizerRoute: typeof PortfolioIdOptimizerRoute
  PortfolioIdReportRoute: typeof PortfolioIdReportRoute
  PortfolioIdSmaReportRoute: typeof PortfolioIdSmaReportRoute
  PortfolioIdSummaryRoute: typeof PortfolioIdSummaryRoute
}

const PortfolioIdRouteChildren: PortfolioIdRouteChildren = {
  PortfolioIdAnalyticsRoute: PortfolioIdAnalyticsRoute,
  PortfolioIdAttributionRoute: PortfolioIdAttributionRoute,
  PortfolioIdFxRiskRoute: PortfolioIdFxRiskRoute,
  PortfolioIdOptimizerRoute: PortfolioIdOptimizerRoute,
  PortfolioIdReportRoute: PortfolioIdReportRoute,
  PortfolioIdSmaReportRoute: PortfolioIdSmaReportRoute,
  PortfolioIdSummaryRoute: PortfolioIdSummaryRoute,
}

const PortfolioIdRouteWithChildren = PortfolioIdRoute._addFileChildren(
  PortfolioIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BrokerBlocksRoute: BrokerBlocksRoute,
  CompareRoute: CompareRoute,
  DailyReportRoute: DailyReportRoute,
  GetStartedRoute: GetStartedRoute,
  HedgeFallbacksRoute: HedgeFallbacksRoute,
  LearnRoute: LearnRoute,
  MarketsRoute: MarketsRoute,
  ResearchRoute: ResearchRoute,
  SaxoReconnectRoute: SaxoReconnectRoute,
  SaxoStatusRoute: SaxoStatusRoute,
  SettingsRoute: SettingsRoute,
  SimulationReportRoute: SimulationReportRoute,
  SpilloverRoute: SpilloverRoute,
  TradesRoute: TradesRoute,
  LongHorizonIdRoute: LongHorizonIdRoute,
  MarketSymbolRoute: MarketSymbolRoute,
  PortfolioIdRoute: PortfolioIdRouteWithChildren,
  WalkForwardIdRoute: WalkForwardIdRoute,
  ApiBrokerBlocksClearRoute: ApiBrokerBlocksClearRoute,
  ApiPublicAlgoRegimeAutotuneCronRoute: ApiPublicAlgoRegimeAutotuneCronRoute,
  ApiPublicNewsPreviewRoute: ApiPublicNewsPreviewRoute,
  ApiPublicSetupScanCronRoute: ApiPublicSetupScanCronRoute,
  ApiPublicHooksAiGatewayHealthRoute: ApiPublicHooksAiGatewayHealthRoute,
  ApiPublicHooksBackfillDailyEquityChangesRoute:
    ApiPublicHooksBackfillDailyEquityChangesRoute,
  ApiPublicHooksBackfillIntradayEquityRoute:
    ApiPublicHooksBackfillIntradayEquityRoute,
  ApiPublicHooksBatchRetrainRoute: ApiPublicHooksBatchRetrainRoute,
  ApiPublicHooksBreakoutExpectancyRoute: ApiPublicHooksBreakoutExpectancyRoute,
  ApiPublicHooksCorporateActionDeadlinesRoute:
    ApiPublicHooksCorporateActionDeadlinesRoute,
  ApiPublicHooksCreditBudgetCheckRoute: ApiPublicHooksCreditBudgetCheckRoute,
  ApiPublicHooksDailyRunRoute: ApiPublicHooksDailyRunRoute,
  ApiPublicHooksDailySummaryRoute: ApiPublicHooksDailySummaryRoute,
  ApiPublicHooksHourlyRunRoute: ApiPublicHooksHourlyRunRoute,
  ApiPublicHooksInsiderScanRoute: ApiPublicHooksInsiderScanRoute,
  ApiPublicHooksLiveReconcileRoute: ApiPublicHooksLiveReconcileRoute,
  ApiPublicHooksMarketOpenAlertsRoute: ApiPublicHooksMarketOpenAlertsRoute,
  ApiPublicHooksNewsBackfillRoute: ApiPublicHooksNewsBackfillRoute,
  ApiPublicHooksNewsRefreshRoute: ApiPublicHooksNewsRefreshRoute,
  ApiPublicHooksOrphanOrderSweepRoute: ApiPublicHooksOrphanOrderSweepRoute,
  ApiPublicHooksSaxoAccountKeyAuditRoute:
    ApiPublicHooksSaxoAccountKeyAuditRoute,
  ApiPublicHooksSaxoRefreshRoute: ApiPublicHooksSaxoRefreshRoute,
  ApiPublicHooksTickerWatchRoute: ApiPublicHooksTickerWatchRoute,
  ApiPublicHooksTranslationRefreshRoute: ApiPublicHooksTranslationRefreshRoute,
  ApiPublicHooksValuationDriftRoute: ApiPublicHooksValuationDriftRoute,
  ApiPublicSaxoCallbackRoute: ApiPublicSaxoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
